Glue Gun
JoshMate/JoshMate_TTT pull request #20
Opened 2022-03-16 17:35 UTC by vmiddlemost

Added glue gun to normal care package loot

2022-03-16 21:19 UTC, JoshMate requested changes
5 Comments.

2022-03-16 21:19 UTC, JoshMate commented on JoshMate_TTT2/gamemodes/terrortown/entities/weapons/weapon_jm_zloot_gluegun.lua
> +   SWEP.Icon               = "vgui/ttt/joshmate/icon_jm_pulsepad.png"
Needs A unique Icon.

2022-03-16 21:19 UTC, JoshMate commented on JoshMate_TTT2/gamemodes/terrortown/entities/weapons/weapon_jm_zloot_gluegun.lua
> +SWEP.Primary.Sound         = "shoot_poisondart.wav"
Needs A unique sound. (Non Traitors weapons shouldn't have silenced sounds, could cause issues)

2022-03-16 21:19 UTC, JoshMate commented on JoshMate_TTT2/gamemodes/terrortown/entities/weapons/weapon_jm_zloot_gluegun.lua
> +local GlueGun_Range         = 1200
Variables should start with a lowercase, and don't mix cases (variableNameLikeThis or variable_name_like_this) (do as I say not as I do) (:cope)

2022-03-16 21:19 UTC, JoshMate commented on JoshMate_TTT2/gamemodes/terrortown/entities/weapons/weapon_jm_zloot_gluegun.lua
> +      weaponOwner:ChatPrint("[Glue Gun]: You've glued someone!")
ChatPrint is deprecated, we now use " JM_Function_PrintChat(weaponOwner, "Equipment", ent:Nick() .. " has been Poisoned!" )"

2022-03-16 21:19 UTC, JoshMate commented on JoshMate_TTT2/gamemodes/terrortown/entities/weapons/weapon_jm_zloot_gluegun.lua
> +      JM_RemoveBuffFromThisPlayer("jm_buff_gluegrenade",ent)
Unless you really want to be directly coupled with the glue grenades balance, I'd suggest creating a new buff that can be balanced independently of the glue grenade. but depends on what you are trying to do.

2022-03-17 09:40 UTC, vmiddlemost commented on JoshMate_TTT2/gamemodes/terrortown/entities/weapons/weapon_jm_zloot_gluegun.lua
> +   SWEP.Icon               = "vgui/ttt/joshmate/icon_jm_pulsepad.png"
Changed icon to a famas with blue backdrop

2022-03-17 10:07 UTC, JoshMate commented on JoshMate_TTT2/gamemodes/terrortown/entities/weapons/weapon_jm_zloot_gluegun.lua
> +   util.Effect("cball_explode", effect, true, true)
You could replace this "Sparks Effect" with the glue grenade yellow glue splat effect, you may be able to copy and paste the effect code from there, but you may have to tweak arguments a little.

2022-03-17 11:40 UTC, vmiddlemost commented on JoshMate_TTT2/gamemodes/terrortown/entities/weapons/weapon_jm_zloot_gluegun.lua
> +SWEP.Primary.Sound         = "shoot_poisondart.wav"
Created and added new "shoot_gluegun.wav" sound to replace place holder sound.

2022-03-17 11:42 UTC, vmiddlemost commented on JoshMate_TTT2/gamemodes/terrortown/entities/weapons/weapon_jm_zloot_gluegun.lua
> +local GlueGun_Range         = 1200
GlueGun_Range -> glueGunRange

2022-03-17 11:44 UTC, vmiddlemost commented on JoshMate_TTT2/gamemodes/terrortown/entities/weapons/weapon_jm_zloot_gluegun.lua
> +      weaponOwner:ChatPrint("[Glue Gun]: You've glued someone!")
Changed line to new line.

2022-03-17 11:45 UTC, vmiddlemost commented on JoshMate_TTT2/gamemodes/terrortown/entities/weapons/weapon_jm_zloot_gluegun.lua
> +      JM_RemoveBuffFromThisPlayer("jm_buff_gluegrenade",ent)
Leaving this un-changed as I'm happy with keeping the glue gun effect as the same as the glue grenade effect... for now >:)

2022-03-17 12:11 UTC, vmiddlemost commented on JoshMate_TTT2/gamemodes/terrortown/entities/weapons/weapon_jm_zloot_gluegun.lua
> +   util.Effect("cball_explode", effect, true, true)
Changed sparks effect to match glue grenade effect for lore consistency

2022-03-18 11:25 UTC, JoshMate approved these changes

2022-03-18 11:28 UTC, merged